### ISSUE TITLE
Affichage incomplet du graphe au chargement d'une histoire de l'Atelier

### ISSUE THREAD

**Issue by benoit-smith** [kaelhem/moiki-bug-tracking#1]
Lorsqu'on charge une histoire préalablement enregistrée dans l'Atelier, le graphe s'affiche sans ses chemins, seulement avec ses nœuds déconnectés (navigateur : Firefox dernière version, sous Windows 10).
![no_paths](https://user-images.githubusercontent.com/62805693/85735350-df721c00-b6fd-11ea-99b5-0036337454ac.png)

Toute modification de l'histoire déclenche le rechargement correct du graphe.

**Comment by benoit-smith** [comment]
Bug non reproduit sur Chrome ni sur Edge (Windows 10).

**Comment by benoit-smith** [comment]
Bug reproduit sur Firefox pour Linux.

**Comment by kaelhem** [comment]
Le problème d'affichage des liens est corrigé. Il y a toutefois encore un soucis sur les "têtes des flèches" qui n'apparaissent que pour les liens nouvellement créés. Je fais un autre ticket pour cela, car c'est beaucoup plus mineur.
