### ISSUE TITLE
Augmenter la limite de nombre de thèmes

### ISSUE THREAD

**Issue by wardrob-lev** [kaelhem/moiki-bug-tracking#11]
Bonjour,
la limite actuelle du nombre de thèmes que l'on peut créer est vraiment très basse pour une longue fiction, surtout si on utilise plusieurs thèmes pour la stylisation des boutons.

Je suis sur une fiction pas terminée de plus de 6000 mots et j'arrive à cours des 10 thèmes possibles, même en en réutilisant certains pour les boutons. 
Pour être à l'aise, une limite de 20 thèmes serait beaucoup plus confortable, et si cette limite n'est pas simplement due à une restriction nécessaires des upload (images ?), il serait vraiment très utile de l'élever encore un peu. 
Ça permettrait d'avoir des écrans titres intermédiaires entre les séquences, un large panel d'ambiances colorées (même sans images), tout ça sans sacrifier le choix des styles de boutons (j'en utilise 3 minimum).

**Comment by kaelhem** [comment]
Fait en version 0.8.1. La limite est maintenant de 20 thèmes.
