### ISSUE TITLE
Pouvoir voir la date de publication en format [JJ/MM/AA] au lieu de [il y a {x temps}]

### ISSUE THREAD

**Issue by manonamora** [kaelhem/moiki-bug-tracking#13]
C'est pas vraiment un bug (et c'est plus applicable à Moiki le site/Social Club que Moiki le programme).
Mais ce serait cool de pouvoir voir la date de publication dans un autre format que [il y a {x temps}]. 
Genre un tooltip avec la date qui apparaît en passant la souris sur [publié il y a {x temps}]?

**Comment by kaelhem** [comment]
J'avais fait un truc pour cela, dans la partie historique des pages de présentation d'une histoire.
<img width="417" alt="Capture d’écran 2024-01-16 à 18 58 00" src="https://github.com/kaelhem/moiki-bug-tracking/assets/1114181/8fdf2ce4-14cd-408b-867b-8e7fac8389a9">

Ce n'est pas suffisant ?

**Comment by manonamora** [comment]
Ah oups! J'avais pas descendu jusqu'en bas de la page! Désolé et merci!!
