### ISSUE TITLE
Nom d'onglet sur page d'accueil

### ISSUE THREAD

**Issue by mythonirie** [kaelhem/moiki-bug-tracking#14]
Quand on est une une page spécifique (par exemple la page de la FAQ) et qu'on clique sur l'icone de Moiki pour aller sur la page d'accueil, le nom de l'onglet ne se met pas à jour.

![image](https://github.com/kaelhem/moiki-bug-tracking/assets/129536167/381ea70c-4d68-4976-8c68-4d1ae4c91f07)

Présent sur Windows, Firefox 122.0.1 (64 bits)

**Comment by kaelhem** [comment]
Ha bien vu ! Il semblerait que ne ce soit pas systématique, et que cela ne se produise effectivement qu'au retour sur l'accueil. Je peux sûrement corriger ça !

**Comment by kaelhem** [comment]
Ca semble corrigé en 0.8.1
