### ISSUE TITLE
L'export au format webapp garde le lien vers le cloud de moiki pour les musiques ajoutées localement 

### ISSUE THREAD

**Issue by wardrob-lev** [kaelhem/moiki-bug-tracking#15]
J'ai ajouté une musique (Creative commons) dans mon histoire, mais en cherchant pourquoi la musique ne se lançait pas après avoir uploadé ma webapp sur itch, alors que tout fonctionne bien dans le navigateur autrement avec mon export, j'ai découvert que le lien du fichier mp3 qui est utilisé dans l'histoire n'est pas celui du fichier local inclus à l'export, mais celui du cloud de moiki. Et donc la musique ne se lance pas sur Itch [Blocage d’une requête multiorigines (Cross-Origin Request)].

Le fichier mp3 existe bien en local dans le dossier sons de la webapp, donc le lien live utilisé par l'éditeur moiki devrait être remplacé par cette nouvelle URI pendant l'export, ce qui n'a pas l'air de se faire correctement. J'ai essayé de ré-exporter, même résultat. 

Un aperçu de ce qui se passe avec la musique dans la console quand j'éxécute ma webapp exportée dans le navigateur en local :
![local_music_cloud](https://github.com/user-attachments/assets/c8463b32-1d2d-42e7-850c-f3de11313751)

Est-ce qu'il y a un moyen de contourner ça rapidement d'une façon ou d'une autre ? J'avais uploadé ma fiction interactive sur Itch pour une jam qui se termine le 31 octobre, et il ne reste que 4 jours pour que je puisse avoir une version qui fonctionne correctement à ré-uploader... c'est urgent.

Merci d'avance pour toute aide.

**Comment by kaelhem** [comment]
Argh! Je check et corrige ça au plus vite. C'est une belle regression 😖

**Comment by wardrob-lev** [comment]
C'est bon le problème est réglé dans la nouvelle version de Moiki.
Merci beaucoup pour la rapidité !
