### ISSUE TITLE
L'exporteur de la page "Mes histoires" n'exporte pas le nom d'utilisateur⋅ice

### ISSUE THREAD

**Issue by wardrob-lev** [kaelhem/moiki-bug-tracking#16]
La webapp exportée par le raccourci situé sur la page "Mes histoires" de l'atelier n'insère pas le nom d'utilisateur⋅ice dans la fenêtre de démarrage de la webapp, ce qui donne le sous-titre suivant : "Une histoire de Inconnu"

![Inconnu](https://github.com/user-attachments/assets/ce424ebf-f32a-414d-9f28-f9dc1c4849c2)

Depuis l'éditeur d'histoire par contre, le nom @ apparaît bien dans la Webapp exportée.

**Comment by wardrob-lev** [comment]
... et je constate aussi que le nom affiché est différent dans la webapp exportée et dans l'histoire sur Moiki. Dans la webapp j'ai le pseudo @xxxxxxxxx, alors que sur Moiki j'ai Prénom et Nom.  
est-ce qu'il y a un moyen d'unifier ça et de choisir ou savoir ce qui va apparaître ? Un nom d'auteur⋅ice peut être préférable à un pseudo utilisateur⋅ice dans certains cas.

**Comment by kaelhem** [comment]
Merci pour ce retour. Malheureusement, je ne vais pas être en mesure de corriger cela rapidement (je suis en vacances...).

Le premier soucis est un bug (oubli de ma part, mais il y a une solution de contournement donc pas urgent).

Pour le second problème, il n'existe pas de manière de choisir actuellement ce qui sera affiché comme nom, mais c'est une bonne idée, je pourrai l'ajouter dans une future version. En attendant, tu peux ajouter un pseudonyme dans ton compte depuis la page https://moiki.fr/profile/account . Ce sera alors en principe ce pseudo qui sera affiché comme nom.

**Comment by kaelhem** [comment]
corrigé partiellement en v0.8.15
Je le clarifierai dans la documentation, mais la règle d'affichage est la suivante :
* si un pseudonyme est renseigné, c'est celui-ci qui est affiché
* sinon : 
  + si c'est une histoire publiée sur le SocialClub, c'est l'id public (@XXXX) qui apparait
  + si c'est une histoire privée (lien direct), c'est le nom / prénom renseigné dans le profil utilisateur qui est affiché
  
Pour les histoires exportées, c'est toujours le pseudo en priorité, mais je dois encore corriger le cas où il n'y a pas de pseudo : actuellement, si l'utilisateur est inscrit sur le Social Club c'est son id public qui est affiché (@XXXX) sinon, c'est son nom / prénom. Il me reste donc à enlever l'id public des exports pour que ça fonctionne de la même manière que les histoires privées.

**Comment by kaelhem** [comment]
Corrigé en version 0.8.16.
