### ISSUE TITLE
La licence des sons ajouté localement n'apparaît pas dans les crédits

### ISSUE THREAD

**Issue by wardrob-lev** [kaelhem/moiki-bug-tracking#17]
En cliquant sur "voir les crédits" depuis le menu de l'histoire, je constate que le champs crédit renseigné pour les images apparaît bien comme je les ai renseigné, mais pas pour la musique. 

Voila ce que j'ai renseigné dans l'éditeur :

![Screenshot 2024-10-27 at 21-43-39 Atelier NARTHEX](https://github.com/user-attachments/assets/b56e3b61-8a49-4f54-b2b7-5d0ed972d2a3)

Et voila ce qui apparaît :` Licence : ???`

![credits_son](https://github.com/user-attachments/assets/02ace9ef-b676-4e96-a99d-982f9ab1f911)

**Comment by kaelhem** [comment]
fixé en v0.8.15
