### ISSUE TITLE
Nombre limités de choix par séquence

### ISSUE THREAD

**Issue by benoit-smith** [kaelhem/moiki-bug-tracking#2]
Il semble qu'on ne puisse pas ajouter plus de 3 (trois) choix par séquence. Cette limite me paraît un peu sévère (certains auteurs pousseraient bien le vice jusqu'à proposer 6 ou 7 choix pour une séquence).

**Comment by kaelhem** [comment]
Le nombre de choix est effectivement limité à 3 pour plusieurs raisons. Le première étant que les histoires réalisées doivent être jouables sur mobile et tenir dans l'écran. Cette contrainte permet également de limiter la complexité des histoires afin d'éviter que des auteurs ne se retrouvent bloqués dans un scénario où ils auraient été trop "gourmands".
Toutefois, je vais laisser ce ticket ouvert et réfléchir à la question.

En attendant, il est toujours possible de cumuler les séquences de type "choix". Y'a t'il un cas d'usage spécifique bloquant ?

**Comment by benoit-smith** [comment]
Attendu la finalité du logiciel (le support mobile), je comprends mieux la limitation. Pour ma part, je testais dans le cadre plus spécifique d'un projet de livre-jeu, où je peux me permettre d'être... "gourmand" ;-)

**Comment by kaelhem** [comment]
Je réfléchirai tout de même à la question (avec par exemple un player différent de l'existant, acceptant du scroll... façon _ink_) mais j'ai plusieurs idées que j'aimerai développer avant cela.
