### ISSUE TITLE
Site illisible sur IE 11

### ISSUE THREAD

**Issue by benoit-smith** [kaelhem/moiki-bug-tracking#3]
Quand on accède à moiki.fr avec IE 11 (sous Windows 10), on tombe sur une page blanche.

**Comment by kaelhem** [comment]
faut vraiment que je teste sur windows :)

**Comment by kaelhem** [comment]
c'est spécifique IE ? ou ça fait la même chose sur FF/Chrome ?

**Comment by benoit-smith** [comment]
Spécifique IE 11 (pas testé les versions plus anciennes).

**Comment by kaelhem** [comment]
Le site s'affiche maintenant. Je n'irai pas jusqu'à dire que c'est parfait, loin de là, mais c'est fonctionnel et au moins on arrive pas sur une page blanche. Vu les stats d'utilisation d'IE, les problèmes restants ne seront surement jamais corrigés.
