### ISSUE TITLE
[Recherche d'icone] Scroll fait tout disparaitre

### ISSUE THREAD

**Issue by Selsynn** [kaelhem/moiki-bug-tracking#5]
Bonjour,

Si on sélectionne un mot-clef avec plus d'un screen de résultat (woman; fire, par ex) la recherche d'icone laisse apparaitre les premiers résultat et cache tout dès qu'on commence à selectionner ou a scroller pour chercher l'icone adequate.

Merci

**Comment by kaelhem** [comment]
Bonjour,
dans quel navigateur ? Je ne reproduis ni dans chrome, ni dans firefox...

**Comment by Selsynn** [comment]
Firefox 77.0.1, sur windows 10.

Ce qui est bizarre, c'est que des que je regarde avec l'explorateur en meme temps et que je selectionne un des div, cela semble forcer a redessiner les icones et du coup je vois a nouveau les icones.

Pour etre parfaitement claire, le probleme c'est que je me retrouve avec cet ecran:

![image](https://user-images.githubusercontent.com/7371599/86316523-cf68a980-bbe1-11ea-9400-78c689483e54.png)

**Comment by kaelhem** [comment]
J'ai réussi à reproduire le problème sur FF 77.0.1 (windows uniquement). En faisant la mise à jour vers FF 78.0.1 (dernière version) il semblerait que le pb ait disparu... Pouvez-vous confirmer cela ?

**Comment by Selsynn** [comment]
Okay, mon firefox a fait la mise a jour avant que je redemarre. Merci beaucoup pour le temps passe sur le probleme. Je vais fermer l'issue. Merci beaucoup pour la rapidite de reponse
