### ISSUE TITLE
Atelier inaccessible sur un écran de téléphone mobile en mode Portrait

### ISSUE THREAD

**Issue by benoit-smith** [kaelhem/moiki-bug-tracking#6]
Sur un écran de téléphone mobile orienté en "portrait" (vertical), le bouton Atelier sur la page moiki.fr d'un utilisateur connecté est invisible.
Il apparaît quand on oriente l'écran en "paysage" (horizontal).

**Comment by kaelhem** [comment]
Oui, c'est fait exprès :) L'éditeur n'est pas du tout prévu pour être utilisé sur mobile en mode portrait. On peut y accéder en passant son téléphone en mode paysage, cliquer sur le bouton pour ouvrir la page Atelier et le remettre en mode portrait. Mais ce n'est clairement pas pratique. Ça peut éventuellement dépanner lorsqu'on veut corriger une faute, mais cet usage n'est pas à encourager.
