### ISSUE TITLE
routine et passage

### ISSUE THREAD

**Issue by mythonirie** [kaelhem/moiki-bug-tracking#7]
Lorsqu'on est sur une histoire en mode expert avec une routine, on ne peux pas utiliser la condition de passage par une séquence d'une routine en dehors de la routine. 

On ne peux donc pas faire de condition de passage sur les séquences d'une routine dans le corps principal du jeu ou dans les événements. 

Je n'arrive pas a savoir si c'est voulu ou pas.

**Comment by kaelhem** [comment]
Hello, oui c’est voulu.
Une routine peut être considérée comme « une histoire dans l’histoire ». Les conditions de passage sont donc limitées à leur scope. Il est possible que cela évolue à l’avenir, mais pas tout de suite…
De plus, concernant les conditions de passage sur les événements il n’est possible que de cibler les séquences du graphe principal (de même que sur les conditions liées à l’affichage des jauges).

Il est toujours possible d’utiliser des variables compteur pour palier à cela.
