### ISSUE TITLE
Mauvais temps indiqué avec plusieurs minuteurs successifs

### ISSUE THREAD

**Issue by wardrob-lev** [kaelhem/moiki-bug-tracking#8]
J'ai plusieurs minuteurs successifs sur des écrans qui se suivent, avec un décompte que je mets de plus en plus court à chaque fois : le premier est à 30 sec, ensuite 15 sec, et encore après 7 sec.

Le bug se produit sur le 3e minuteur (4e écran dans l'histoire de débug que j'ai mise en lien). Le minuteur devrait débuter à 7 secondes, mais il commence à 15 secondes comme celui de l'écran d'avant. Et en plus le décompte se fait en nombres mais le petit cadran blanc ne commence à s'animer lui qu'à partir de 7 secondes...

J'ai tenté de reproduire le bug avec une histoire neuve, mais je n'y arrive pas (il y plein de sons et d'image alors c'est un peu compliqué de faire ça bien). Donc ici le bug n'apparaît pas : [https://moiki.fr/story/652fc490b86d7500396cf937](https://moiki.fr/story/652fc490b86d7500396cf937)
Mais ici, il se produit : [https://moiki.fr/story/652fc81db86d7500396d0aa6](https://moiki.fr/story/652fc81db86d7500396d0aa6)

L'export JSON de l'histoire qui bug est là (expire dans 5 jours) : [https://drop.chapril.org/download/91a2ae943ea06d53/#87wJnjrD3TxSAZ16K2s7dw](https://drop.chapril.org/download/91a2ae943ea06d53/#87wJnjrD3TxSAZ16K2s7dw)

**Comment by kaelhem** [comment]
Corrigé en version 0.7.9 ! Merci :)
