### ISSUE TITLE
Le raccourci de conditions pour les visibilités de choix ne fonctionne pas

### ISSUE THREAD

**Issue by wardrob-lev** [kaelhem/moiki-bug-tracking#9]
Bonjour,
en créant des choix multiples qui doivent s'afficher sous condition d'un passage ou non par une séquence précise, je me suis rendu compte que le raccourci direct "Condition"  visible dans la boîte des choix sous l'éditeur de séquence n'était pas du tout pris en compte. Les conditions appliquées par ce raccourci ne fonctionnent pas.

Par contre **les mêmes conditions fonctionnent** si on entre d'abord dans le menu "Modifier le texte de ce choix" à côté d'un choix, et qu'on clique ensuite sur le bouton "Condtion" qui s'y trouve aussi.

J'ai créé une histoire test pour reproduire le bug : https://moiki.fr/story/654b87ea87ad6b00392bf087

et le fichier JSON est là : https://lufi.ethibox.fr/r/kyJdXREHT8#H+SFw3o3GzGWcytplfnWXtAoG08ncgRkUdKBnCBAtUY=

**Comment by kaelhem** [comment]
Bonjour,
Il semblerait qu'il y ait une confusion entre "conditions" et "conditions de visibilité".
Les conditions, servent à diriger les joueurs vers un embranchement ou un autre en fonction des critères de la condition.
Les conditions de visibilité permettent elles d'afficher ou non un choix en fonction des critères. C'est une option disponible uniquement sur les choix, et on peut y accéder par le bouton avec un engrenage dans le bloc du choix, ou par la fenêtre d'édition du texte de ce choix.
Cela est expliqué dans la documentation, ici : https://moiki.fr/documentation/actions-conditions

**Comment by wardrob-lev** [comment]
> Bonjour, Il semblerait qu'il y ait une confusion entre "conditions" et "conditions de visibilité".

Oui j'avais très mal compris l'usage des conditions pour changer de sequence de destination ! Désolé.
